server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://39.97.177.78:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: WangChen?981203
    driver-class-name: com.mysql.cj.jdbc.Driver
    cloud:
      zookeeper:
        connect-string: localhost:2181
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL
logging:
  level:
    com.yc.springcloud81.misprovider.dao: debug
